Update nightly-build.yml

diff --git a/.github/workflows/nightly-build.yml b/.github/workflows/nightly-build.yml
--- a/.github/workflows/nightly-build.yml
+++ b/.github/workflows/nightly-build.yml
@@ -200,7 +200,8 @@ jobs:
             echo "Terminating EC2 instance ${{ needs.Run-Smoketest.outputs.instance_id }}..."
             aws ec2 terminate-instances --instance-ids ${{ needs.Run-Smoketest.outputs.instance_id }}
           else
-            echo "No EC2 instance was launched, skipping termination."
+            echo "No EC2 instance was launched, failing termination."
+            exit 1
           fi
           
   Remove-Docker-Images:
